import { createHmac, timingSafeEqual } from 'node:crypto'
import {
  PROTOCOL_VERSION,
  RECORD_DOMAIN,
  CURSOR_DOMAIN,
  LIMITS,
  assertNoDuplicateTopLevelKeys,
  bodyHash,
  canonicalRecordKey,
  hasInvalidUnicode,
  isBodyHash,
  isCanonicalBase64,
  isIdentityKey,
  isRecordKey,
  isUint64DecimalString,
  sha256Bytes,
  sha256Hex,
  utf8ByteLength,
  utf8Bytes,
  validateDirection,
  validateEncryptedBody,
  validateMessageBox,
  validateMessageId,
} from './canonical-runtime.js'

export {
  PROTOCOL_VERSION,
  RECORD_DOMAIN,
  CURSOR_DOMAIN,
  LIMITS,
  assertNoDuplicateTopLevelKeys,
  bodyHash,
  canonicalRecordKey,
  hasInvalidUnicode,
  isBodyHash,
  isCanonicalBase64,
  isIdentityKey,
  isRecordKey,
  isUint64DecimalString,
  sha256Bytes,
  sha256Hex,
  utf8ByteLength,
  utf8Bytes,
  validateDirection,
  validateEncryptedBody,
  validateMessageBox,
  validateMessageId,
} from './canonical-runtime.js'

/**
 * M1 shared protocol: canonical record identity, validation, limits, error
 * envelope, page/cursor contracts and cross-language conformance vectors.
 *
 * Sources: PRD.md, ADR-001-durable-history.md, docs/M0-DECISIONS.md.
 * M0 executable proof lives in src/m0-*.mjs; this module freezes the wire
 * semantics M2/M3 must implement. No I/O, no database, no network.
 *
 * @typedef {'inbound'|'outbound'} Direction
 * @typedef {'prepared'|'received'|'unknown'|'accepted'|'failed'} DeliveryState
 * @typedef {'changes'|'snapshot'} Feed
 */

export const ROUTES = Object.freeze({
  archiveBatch: 'POST /v1/history/records',
  snapshot: 'GET /v1/history/snapshot',
  changes: 'GET /v1/history/changes',
  patchState: 'PATCH /v1/history/records/{recordKey}/state',
  deleteRecord: 'DELETE /v1/history/records/{recordKey}',
  deleteAll: 'DELETE /v1/history/records',
  capabilities: 'GET /v1/history/capabilities',
  liveness: 'GET /healthz',
  readiness: 'GET /ready',
})

/** Finite initial defaults (M0-DECISIONS). Planning defaults, not capacity promises. */
export const DIRECTIONS = Object.freeze(['inbound', 'outbound'])
export const DELIVERY_STATES = Object.freeze(['prepared', 'received', 'unknown', 'accepted', 'failed'])
/** States permitted on archive creation; all other states use patchState. */
export const INITIAL_DELIVERY_STATES = Object.freeze(['prepared', 'received'])
export const OUTBOUND_TERMINAL_BLOCK_SEND = Object.freeze(['prepared', 'unknown', 'accepted'])
export const FEEDS = Object.freeze(['changes', 'snapshot'])

/** Stable PRD error classes. Descriptions must never echo ciphertext/plaintext. */
export const ERROR_CODES = Object.freeze([
  'ERR_AUTHENTICATION_REQUIRED',
  'ERR_FORBIDDEN',
  'ERR_INVALID_RECORD',
  'ERR_REQUEST_TOO_LARGE',
  'ERR_QUOTA_EXCEEDED',
  'ERR_IMMUTABLE_CONFLICT',
  'ERR_CURSOR_EXPIRED',
  'ERR_INVALID_CURSOR',
  'ERR_REVISION_CONFLICT',
  'ERR_EPOCH_CHANGED',
  'ERR_RATE_LIMITED',
  'ERR_UNAVAILABLE',
  'ERR_INTERNAL',
  // Transport policy (M0-proven, re-tested in M3).
  'ERR_PAID_TRANSPORT_UNSUPPORTED',
  // Replay-safe mutations (M1 rereview): idempotency-key reuse with different
  // input, and generation-counter exhaustion beyond uint64.
  'ERR_IDEMPOTENCY_CONFLICT',
  'ERR_EPOCH_EXHAUSTED',
])

// Precise JSON-Schema pattern for 0..2^64-1 (no leading zeros). Generated by
// prefix enumeration over "18446744073709551615": 1..19 digit canonials are
// always below max; 20-digit values are constrained digit-by-digit.
export const UINT64_CANONICAL_PATTERN =
  '^((0|[1-9][0-9]{0,18})|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|1844674407370955[0-0][0-9]{3}|18446744073709551[0-5][0-9]{2}|184467440737095516[0-0][0-9]{1}|1844674407370955161[0-4][0-9]{0}|18446744073709551615)$'
const EPOCH_RE = /^[A-Za-z0-9:_-]{1,128}$/
const IDEMPOTENCY_RE = /^[A-Za-z0-9_-]{1,128}$/

export function validateEpoch(value) {
  if (typeof value !== 'string' || !EPOCH_RE.test(value)) throw new TypeError('epoch must be 1..128 [A-Za-z0-9:_-] chars')
  return value
}

export function validateIdempotencyKey(value) {
  if (typeof value !== 'string' || !IDEMPOTENCY_RE.test(value)) {
    throw new TypeError('idempotencyKey must be 1..128 [A-Za-z0-9_-] chars')
  }
  return value
}

export function validateChangeSequence(value, name = 'changeSequence') {
  if (!isUint64DecimalString(value)) throw new TypeError(`${name} must be a uint64 decimal string`)
  return value
}

export function compareUint64Decimal(a, b) {
  validateChangeSequence(a, 'a')
  validateChangeSequence(b, 'b')
  const x = BigInt(a)
  const y = BigInt(b)
  return x < y ? -1 : x > y ? 1 : 0
}

/** Inbound recipient == owner; outbound sender == owner. Self-send has both. */
export function assertOwnerDirection({ ownerIdentityKey, direction, sender, recipient }) {
  if (!isIdentityKey(ownerIdentityKey)) throw new TypeError('ownerIdentityKey must be a compressed lowercase identity key')
  validateDirection(direction)
  if (!isIdentityKey(sender)) throw new TypeError('sender must be a compressed lowercase identity key')
  if (!isIdentityKey(recipient)) throw new TypeError('recipient must be a compressed lowercase identity key')
  if (direction === 'inbound' && recipient !== ownerIdentityKey) {
    throw new RangeError('inbound recipient must equal the authenticated owner')
  }
  if (direction === 'outbound' && sender !== ownerIdentityKey) {
    throw new RangeError('outbound sender must equal the authenticated owner')
  }
}

/**
 * Server-side recomputation: recompute bodyHash + recordKey from the caller's
 * fields and compare to supplied values. Returns recomputed values; throws on
 * mismatch so forged keys/hashes never create a second record.
 */
export function recomputeRecordIdentity({ ownerIdentityKey, direction, messageBox, sender, recipient, messageId, body }) {
  validateEncryptedBody(body)
  assertOwnerDirection({ ownerIdentityKey, direction, sender, recipient })
  return {
    bodyHash: bodyHash(body),
    recordKey: canonicalRecordKey({ ownerIdentityKey, direction, messageBox, sender, recipient, messageId }),
  }
}

export function assertArchiveRecordFits({ body }) {
  const bytes = utf8ByteLength(body)
  if (bytes > LIMITS.MAX_BODY_BYTES) {
    const error = new RangeError('body exceeds 1 MiB')
    error.code = 'ERR_REQUEST_TOO_LARGE'
    throw error
  }
  return bytes
}

/** JSON overhead-aware byte accounting. Every allowed record must fit a page. */
export function estimateJsonBytes(value) {
  return Buffer.byteLength(JSON.stringify(value), 'utf8')
}

/**
 * Page fit check including JSON overhead. If a single record alone exceeds the
 * page budget, return a typed error (never an empty continuation loop).
 */
export function checkPageFits({ records, overheadBytes = 512, maxBytes = LIMITS.MAX_PAGE_BYTES, maxRecords = LIMITS.MAX_PAGE_RECORDS } = {}) {
  if (!Array.isArray(records)) throw new TypeError('records must be an array')
  if (records.length > maxRecords) {
    return { ok: false, code: 'ERR_REQUEST_TOO_LARGE', reason: 'page record count exceeds limit' }
  }
  // Account for the serialized records array framing: JSON.stringify(records)
  // is sum(recordBytes) + (n-1) commas + 2 brackets (2 bytes for empty "[]").
  // Undercounting this framing lets a 999-record page exceed MAX_PAGE_BYTES
  // while the estimate still fits (mbs-8g5.2.4.7).
  let total = overheadBytes + 2
  for (let i = 0; i < records.length; i += 1) {
    const record = records[i]
    const bytes = estimateJsonBytes(record)
    // Single record alone in its array: overhead + brackets + record.
    if (bytes + overheadBytes + 2 > maxBytes) {
      return { ok: false, code: 'ERR_REQUEST_TOO_LARGE', reason: 'single record exceeds page budget' }
    }
    total += bytes + (i > 0 ? 1 : 0)
    if (total > maxBytes) {
      return { ok: false, code: 'ERR_REQUEST_TOO_LARGE', reason: 'page bytes exceed limit' }
    }
  }
  return { ok: true, bytes: total }
}

function base64UrlEncode(buffer) {
  return Buffer.from(buffer).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function base64UrlDecode(value) {
  if (typeof value !== 'string' || value.length === 0 || !/^[A-Za-z0-9_-]+$/.test(value)) {
    throw new TypeError('cursor part must be base64url')
  }
  const padded = value.replace(/-/g, '+').replace(/_/g, '/') + '==='.slice((value.length + 3) % 4)
  const decoded = Buffer.from(padded, 'base64')
  // Base64url has unused pad bits for 1- and 2-byte tails. Node's decoder
  // accepts aliases that differ only in those bits, so decode then re-encode
  // and require the exact canonical unpadded spelling before any HMAC check.
  if (base64UrlEncode(decoded) !== value) throw new TypeError('cursor part is not canonical base64url')
  return decoded
}

/**
 * Integrity-protected opaque cursor. Owner binds as HMAC context (not a
 * plaintext field) so a cursor copied across identities fails closed with
 * ERR_INVALID_CURSOR without revealing another owner's activity.
 */
export function createCursor({
  serverSecret,
  ownerIdentityKey,
  epoch,
  feed,
  filterDigest = '',
  watermark,
  position = '0',
  ttlSeconds = LIMITS.CURSOR_TTL_SECONDS,
  nowSeconds = Math.floor(Date.now() / 1000),
}) {
  if (typeof serverSecret !== 'string' || serverSecret.length < 16) {
    throw new TypeError('serverSecret must be at least 16 chars')
  }
  if (!isIdentityKey(ownerIdentityKey)) throw new TypeError('ownerIdentityKey must be a compressed lowercase identity key')
  validateEpoch(epoch)
  if (!FEEDS.includes(feed)) throw new TypeError('feed must be changes or snapshot')
  if (typeof filterDigest !== 'string' || filterDigest.length > 128 || hasInvalidUnicode(filterDigest)) {
    throw new TypeError('filterDigest must be 0..128 chars')
  }
  validateChangeSequence(watermark, 'watermark')
  if (typeof position !== 'string' || position.length === 0 || position.length > 128) {
    throw new TypeError('position must be 1..128 chars')
  }
  const exp = nowSeconds + ttlSeconds
  if (!Number.isSafeInteger(exp) || exp <= 0) throw new TypeError('expiry must be a safe integer')
  const payload = { v: 1, epoch, feed, fd: filterDigest, w: watermark, p: position, exp }
  const json = JSON.stringify(payload)
  const mac = createHmac('sha256', serverSecret).update(`${ownerIdentityKey}|${CURSOR_DOMAIN}|${json}`, 'utf8').digest()
  return `${base64UrlEncode(Buffer.from(json, 'utf8'))}.${base64UrlEncode(mac)}`
}

export function verifyCursor(token, {
  serverSecret,
  ownerIdentityKey,
  expectedEpoch,
  expectedFeed,
  expectedFilterDigest = '',
  nowSeconds = Math.floor(Date.now() / 1000),
} = {}) {
  const invalid = (message) => {
    const error = new TypeError(message)
    error.code = 'ERR_INVALID_CURSOR'
    throw error
  }
  const expired = () => {
    const error = new RangeError('cursor expired; take a full snapshot')
    error.code = 'ERR_CURSOR_EXPIRED'
    throw error
  }
  if (typeof token !== 'string') return invalid('cursor must be a string')
  const parts = token.split('.')
  if (parts.length !== 2) return invalid('cursor must have two parts')
  let json
  try {
    json = base64UrlDecode(parts[0]).toString('utf8')
  } catch {
    return invalid('cursor payload is not base64url')
  }
  let payload
  try {
    payload = JSON.parse(json)
  } catch {
    return invalid('cursor payload is not JSON')
  }
  if (typeof serverSecret !== 'string' || typeof ownerIdentityKey !== 'string') return invalid('cursor verifier misconfigured')
  let providedMac
  try {
    providedMac = base64UrlDecode(parts[1])
  } catch {
    return invalid('cursor authenticator is not base64url')
  }
  if (providedMac.length !== 32) return invalid('cursor authenticator length mismatch')
  const expectedMac = createHmac('sha256', serverSecret).update(`${ownerIdentityKey}|${CURSOR_DOMAIN}|${json}`, 'utf8').digest()
  if (expectedMac.length !== providedMac.length || !timingSafeEqual(expectedMac, providedMac)) {
    return invalid('cursor is not valid for this owner')
  }
  if (payload?.v !== 1 || typeof payload?.exp !== 'number' || !Number.isSafeInteger(payload.exp)) {
    return invalid('cursor claims are malformed')
  }
  if (payload.exp <= nowSeconds) return expired()
  if (expectedEpoch !== undefined && payload.epoch !== expectedEpoch) {
    const error = new RangeError('epoch changed; reconcile against the current snapshot')
    error.code = 'ERR_EPOCH_CHANGED'
    throw error
  }
  if (expectedFeed !== undefined && payload.feed !== expectedFeed) return invalid('cursor feed mismatch')
  if (payload.fd !== expectedFilterDigest) return invalid('cursor filter mismatch')
  try {
    validateChangeSequence(payload.w, 'watermark')
  } catch {
    return invalid('cursor watermark malformed')
  }
  return payload
}

/** HistoryPage shape: final/empty pages still carry checkpoint + watermark + epoch. */
export function validateHistoryPage(page) {
  if (page === null || typeof page !== 'object' || Array.isArray(page)) throw new TypeError('page must be an object')
  if (!Array.isArray(page.records)) throw new TypeError('page.records must be an array')
  if (page.records.length > LIMITS.MAX_PAGE_RECORDS) throw new RangeError('page exceeds record bound')
  if (!(typeof page.nextCursor === 'string' || page.nextCursor === null)) throw new TypeError('page.nextCursor must be string or null')
  if (typeof page.checkpoint !== 'string' || page.checkpoint.length === 0) throw new TypeError('page.checkpoint is required even on empty/final pages')
  if (typeof page.hasMore !== 'boolean') throw new TypeError('page.hasMore must be boolean')
  if (page.hasMore === false && page.nextCursor !== null) throw new TypeError('final page must have nextCursor null')
  if (page.hasMore === true && page.nextCursor === null) throw new TypeError('non-final page must carry nextCursor')
  if (typeof page.watermark !== 'string') throw new TypeError('page.watermark is required')
  validateChangeSequence(page.watermark, 'watermark')
  validateEpoch(page.epoch)
  if (typeof page.serverTime !== 'string' || Number.isNaN(Date.parse(page.serverTime))) {
    throw new TypeError('page.serverTime must be an ISO timestamp')
  }
  return page
}

export function makeStoreError(code, description, retryAfterSeconds) {
  if (!ERROR_CODES.includes(code)) throw new TypeError('unknown error code')
  if (typeof description !== 'string' || description.length === 0) throw new TypeError('description is required')
  // Operator-safe: never echo bodies, keys, signatures or stack traces.
  const error = { status: 'error', code, description }
  if (retryAfterSeconds !== undefined) {
    if (!Number.isSafeInteger(retryAfterSeconds) || retryAfterSeconds < 0) throw new TypeError('retryAfterSeconds must be a non-negative integer')
    error.retryAfterSeconds = retryAfterSeconds
  }
  return error
}

/** Executable M0 vector from docs/M0-DECISIONS.md (cross-language freeze). */
export const M0_VECTOR = Object.freeze({
  ownerIdentityKey: '021111111111111111111111111111111111111111111111111111111111111111',
  direction: 'outbound',
  messageBox: 'general_inbox',
  sender: '021111111111111111111111111111111111111111111111111111111111111111',
  recipient: '032222222222222222222222222222222222222222222222222222222222222222',
  messageId: 'm0-vector-1',
  body: '{"encryptedMessage":"AQ=="}',
  bodyHash: '0084794ecc214b1345494cd74a5758785b703aa54b89b1ff36b5087dc65ff8ce',
  recordKey: '998e052031cfb45d304b54db7bb55abb56c69d2612567bd9eb563229073acbfe',
})

/**
 * Versioned self-contained JSON Schemas (draft 2020-12). Every named schema
 * carries its own `$id` and embedded `$defs`, so a real validator resolves
 * all references with no external documents. Bodies are byte-limited by the
 * repository (UTF-8 bytes), not by `maxLength` character counts alone.
 *
 * Canonical contract: `bodyBytes` is PUBLIC derived metadata — the exact
 * UTF-8 byte length of `body`, server-computed, never client-supplied. It is
 * required in `historyRecord` and present in `stored` batch outcomes. All
 * adapters (memory, SQLite, MySQL) return it; wire and repository projections
 * agree. `owner` is optional in `historyRecord`: repository rows carry it for
 * partition checks, wire pages omit it (implied by authentication).
 */
export const SCHEMA_VERSION = '1'
export const SCHEMA_ID_BASE = 'https://message-box-store/schemas/v1'

const SCHEMA_DEFS = Object.freeze({
  identityKey: { type: 'string', pattern: '^0[23][0-9a-f]{64}$' },
  recordKey: { type: 'string', pattern: '^[0-9a-f]{64}$' },
  bodyHash: { type: 'string', pattern: '^[0-9a-f]{64}$' },
  direction: { type: 'string', enum: ['inbound', 'outbound'] },
  deliveryState: { type: 'string', enum: ['prepared', 'received', 'unknown', 'accepted', 'failed'] },
  changeSequence: { type: 'string', pattern: UINT64_CANONICAL_PATTERN },
  revision: { type: 'string', pattern: UINT64_CANONICAL_PATTERN },
  epoch: { type: 'string', pattern: '^[A-Za-z0-9:_-]{1,128}$' },
  idempotencyKey: { type: 'string', pattern: '^[A-Za-z0-9_-]{1,128}$' },
  messageBox: { type: 'string', minLength: 1, maxLength: LIMITS.MAX_MESSAGE_BOX_LENGTH, pattern: '^(?!\\s*$)[\\s\\S]+$' },
  messageId: { type: 'string', minLength: 1, maxLength: LIMITS.MAX_MESSAGE_ID_LENGTH, pattern: '^(?!\\s*$)[\\s\\S]+$' },
  isoDateTime: { type: 'string', format: 'date-time' },
  bodyBytes: { type: 'integer', minimum: 1, maximum: LIMITS.MAX_BODY_BYTES },
  snapshotId: { type: 'string', pattern: '^snap_[0-9a-f]{32}$' },
  filterHash: { type: 'string', pattern: '^([0-9a-f]{64})?$' },
  snapshotStatus: { type: 'string', enum: ['active', 'invalidated'] },
  snapshotFeed: { type: 'string', const: 'snapshot' },
  errorCode: {
    type: 'string',
    enum: [
      'ERR_AUTHENTICATION_REQUIRED',
      'ERR_FORBIDDEN',
      'ERR_INVALID_RECORD',
      'ERR_REQUEST_TOO_LARGE',
      'ERR_QUOTA_EXCEEDED',
      'ERR_IMMUTABLE_CONFLICT',
      'ERR_CURSOR_EXPIRED',
      'ERR_INVALID_CURSOR',
      'ERR_REVISION_CONFLICT',
      'ERR_EPOCH_CHANGED',
      'ERR_RATE_LIMITED',
      'ERR_UNAVAILABLE',
      'ERR_INTERNAL',
      'ERR_PAID_TRANSPORT_UNSUPPORTED',
      'ERR_IDEMPOTENCY_CONFLICT',
      'ERR_EPOCH_EXHAUSTED',
    ],
  },
})

function namesSchema(name, schema, extraDefs) {
  const defs = extraDefs ? Object.freeze({ ...SCHEMA_DEFS, ...extraDefs }) : SCHEMA_DEFS
  return Object.freeze({ $id: `${SCHEMA_ID_BASE}/${name}.json`, $schema: 'https://json-schema.org/draft/2020-12/schema', ...schema, $defs: defs })
}

// Inline composite shapes (no external $ref). Each page/response schema embeds
// these directly so it compiles alone under strict Ajv.
function historyRecordInline() {
  return {
    type: 'object',
    required: ['recordKey', 'messageId', 'messageBox', 'direction', 'sender', 'recipient', 'body', 'bodyHash', 'bodyBytes', 'deliveryState', 'revision', 'changeSequence', 'createdAt', 'archivedAt'],
    properties: {
      owner: { $ref: '#/$defs/identityKey' },
      recordKey: { $ref: '#/$defs/recordKey' },
      messageId: { $ref: '#/$defs/messageId' },
      messageBox: { $ref: '#/$defs/messageBox' },
      direction: { $ref: '#/$defs/direction' },
      sender: { $ref: '#/$defs/identityKey' },
      recipient: { $ref: '#/$defs/identityKey' },
      body: { type: 'string', minLength: 1 },
      bodyHash: { $ref: '#/$defs/bodyHash' },
      bodyBytes: { $ref: '#/$defs/bodyBytes' },
      deliveryState: { $ref: '#/$defs/deliveryState' },
      revision: { $ref: '#/$defs/revision' },
      changeSequence: { $ref: '#/$defs/changeSequence' },
      createdAt: { $ref: '#/$defs/isoDateTime' },
      archivedAt: { $ref: '#/$defs/isoDateTime' },
      expiresAt: { type: ['string', 'null'], format: 'date-time' },
    },
    additionalProperties: false,
  }
}

function deleteEventInline() {
  return {
    type: 'object',
    required: ['recordKey', 'sequence', 'deletedAt'],
    properties: {
      recordKey: { $ref: '#/$defs/recordKey' },
      sequence: { $ref: '#/$defs/changeSequence' },
      deletedAt: { $ref: '#/$defs/isoDateTime' },
    },
    additionalProperties: false,
  }
}

function batchOutcomeInline() {
  return {
    type: 'object',
    required: ['index', 'outcome'],
    properties: {
      index: { type: 'integer', minimum: 0, maximum: LIMITS.MAX_BATCH_RECORDS - 1 },
      recordKey: { type: ['string', 'null'], pattern: '^[0-9a-f]{64}$' },
      outcome: { type: 'string', enum: ['stored', 'alreadyPresent', 'conflict', 'invalid', 'quotaExceeded', 'deleted', 'epochChanged', 'failed'] },
      errorCode: { $ref: '#/$defs/errorCode' },
      bodyHash: { $ref: '#/$defs/bodyHash' },
      bodyBytes: { $ref: '#/$defs/bodyBytes' },
      sequence: { $ref: '#/$defs/changeSequence' },
    },
    additionalProperties: false,
  }
}

function snapshotFilterInline() {
  return {
    type: 'object',
    properties: {
      direction: { $ref: '#/$defs/direction' },
      messageBox: { $ref: '#/$defs/messageBox' },
      participant: { $ref: '#/$defs/identityKey' },
    },
    additionalProperties: false,
  }
}

export const JSON_SCHEMAS = Object.freeze({
  $defs: SCHEMA_DEFS,
  archiveBatchRequest: namesSchema('archive-batch-request', {
    type: 'object',
    required: ['epoch', 'records'],
    properties: {
      epoch: { $ref: '#/$defs/epoch' },
      records: {
        type: 'array',
        minItems: 1,
        maxItems: LIMITS.MAX_BATCH_RECORDS,
        items: {
          type: 'object',
          required: ['messageId', 'messageBox', 'direction', 'sender', 'recipient', 'body'],
          properties: {
            recordKey: { $ref: '#/$defs/recordKey' },
            messageId: { $ref: '#/$defs/messageId' },
            messageBox: { $ref: '#/$defs/messageBox' },
            direction: { $ref: '#/$defs/direction' },
            sender: { $ref: '#/$defs/identityKey' },
            recipient: { $ref: '#/$defs/identityKey' },
            body: { type: 'string', minLength: 1 },
            bodyHash: { $ref: '#/$defs/bodyHash' },
            // Creation accepts only the two initial states. Terminal and
            // ambiguous states are reached through statePatch.
            deliveryState: { type: 'string', enum: ['prepared', 'received'] },
          },
          additionalProperties: false,
        },
      },
    },
    additionalProperties: false,
  }),
  batchOutcome: namesSchema('batch-outcome', {
    type: 'object',
    required: ['index', 'outcome'],
    properties: {
      index: { type: 'integer', minimum: 0, maximum: LIMITS.MAX_BATCH_RECORDS - 1 },
      recordKey: { type: ['string', 'null'], pattern: '^[0-9a-f]{64}$' },
      outcome: { type: 'string', enum: ['stored', 'alreadyPresent', 'conflict', 'invalid', 'quotaExceeded', 'deleted', 'epochChanged', 'failed'] },
      errorCode: { $ref: '#/$defs/errorCode' },
      bodyHash: { $ref: '#/$defs/bodyHash' },
      bodyBytes: { $ref: '#/$defs/bodyBytes' },
      sequence: { $ref: '#/$defs/changeSequence' },
    },
    additionalProperties: false,
  }),
  archiveBatchResponse: namesSchema('archive-batch-response', {
    type: 'object',
    required: ['epoch', 'committed', 'outcomes'],
    properties: {
      epoch: { $ref: '#/$defs/epoch' },
      committed: { type: 'boolean' },
      outcomes: {
        type: 'array',
        minItems: 1,
        maxItems: LIMITS.MAX_BATCH_RECORDS,
        items: batchOutcomeInline(),
      },
    },
    additionalProperties: false,
  }),
  historyRecord: namesSchema('history-record', {
    type: 'object',
    required: ['recordKey', 'messageId', 'messageBox', 'direction', 'sender', 'recipient', 'body', 'bodyHash', 'bodyBytes', 'deliveryState', 'revision', 'changeSequence', 'createdAt', 'archivedAt'],
    properties: {
      owner: { $ref: '#/$defs/identityKey' },
      recordKey: { $ref: '#/$defs/recordKey' },
      messageId: { $ref: '#/$defs/messageId' },
      messageBox: { $ref: '#/$defs/messageBox' },
      direction: { $ref: '#/$defs/direction' },
      sender: { $ref: '#/$defs/identityKey' },
      recipient: { $ref: '#/$defs/identityKey' },
      body: { type: 'string', minLength: 1 },
      bodyHash: { $ref: '#/$defs/bodyHash' },
      bodyBytes: { $ref: '#/$defs/bodyBytes' },
      deliveryState: { $ref: '#/$defs/deliveryState' },
      revision: { $ref: '#/$defs/revision' },
      changeSequence: { $ref: '#/$defs/changeSequence' },
      createdAt: { $ref: '#/$defs/isoDateTime' },
      archivedAt: { $ref: '#/$defs/isoDateTime' },
      expiresAt: { type: ['string', 'null'], format: 'date-time' },
    },
    additionalProperties: false,
  }),
  historyPage: namesSchema('history-page', {
    type: 'object',
    required: ['records', 'nextCursor', 'checkpoint', 'hasMore', 'watermark', 'epoch', 'serverTime'],
    properties: {
      records: { type: 'array', maxItems: LIMITS.MAX_PAGE_RECORDS, items: { anyOf: [historyRecordInline(), deleteEventInline()] } },
      nextCursor: { type: ['string', 'null'], minLength: 1 },
      checkpoint: { type: 'string', minLength: 1 },
      hasMore: { type: 'boolean' },
      watermark: { $ref: '#/$defs/changeSequence' },
      epoch: { $ref: '#/$defs/epoch' },
      serverTime: { $ref: '#/$defs/isoDateTime' },
    },
    // Final pages carry progress with a null cursor; live pages must continue.
    if: { properties: { hasMore: { const: false } }, required: ['hasMore'] },
    then: { properties: { nextCursor: { type: 'null' } } },
    else: { properties: { nextCursor: { type: 'string', minLength: 1 } } },
    additionalProperties: false,
  }),
  changeFeedPage: namesSchema('change-feed-page', {
    type: 'object',
    required: ['records', 'nextCursor', 'checkpoint', 'hasMore', 'watermark', 'epoch', 'serverTime'],
    properties: {
      records: { type: 'array', maxItems: LIMITS.MAX_PAGE_RECORDS, items: { anyOf: [historyRecordInline(), deleteEventInline()] } },
      nextCursor: { type: ['string', 'null'], minLength: 1 },
      checkpoint: { type: 'string', minLength: 1 },
      hasMore: { type: 'boolean' },
      watermark: { $ref: '#/$defs/changeSequence' },
      epoch: { $ref: '#/$defs/epoch' },
      serverTime: { $ref: '#/$defs/isoDateTime' },
    },
    if: { properties: { hasMore: { const: false } }, required: ['hasMore'] },
    then: { properties: { nextCursor: { type: 'null' } } },
    else: { properties: { nextCursor: { type: 'string', minLength: 1 } } },
    additionalProperties: false,
  }),
  deleteEvent: namesSchema('delete-event', {
    type: 'object',
    required: ['recordKey', 'sequence', 'deletedAt'],
    properties: {
      recordKey: { $ref: '#/$defs/recordKey' },
      sequence: { $ref: '#/$defs/changeSequence' },
      deletedAt: { $ref: '#/$defs/isoDateTime' },
    },
    additionalProperties: false,
  }),
  statePatchRequest: namesSchema('state-patch-request', {
    type: 'object',
    required: ['recordKey', 'newState', 'expectedRevision', 'idempotencyKey'],
    properties: {
      recordKey: { $ref: '#/$defs/recordKey' },
      newState: { $ref: '#/$defs/deliveryState' },
      expectedRevision: { $ref: '#/$defs/revision' },
      idempotencyKey: { $ref: '#/$defs/idempotencyKey' },
    },
    additionalProperties: false,
  }),
  statePatchResponse: namesSchema('state-patch-response', {
    type: 'object',
    required: ['recordKey', 'revision', 'sequence'],
    properties: {
      recordKey: { $ref: '#/$defs/recordKey' },
      revision: { $ref: '#/$defs/revision' },
      sequence: { $ref: '#/$defs/changeSequence' },
      deduped: { type: 'boolean' },
      replayed: { type: 'boolean' },
      ok: { type: 'boolean' },
    },
    additionalProperties: false,
  }),
  deleteRecordRequest: namesSchema('delete-record-request', {
    type: 'object',
    required: ['recordKey'],
    properties: {
      recordKey: { $ref: '#/$defs/recordKey' },
      idempotencyKey: { $ref: '#/$defs/idempotencyKey' },
    },
    additionalProperties: false,
  }),
  deleteRecordResponse: namesSchema('delete-record-response', {
    type: 'object',
    required: ['deleted', 'epoch'],
    properties: {
      deleted: { type: 'boolean' },
      epoch: { $ref: '#/$defs/epoch' },
      sequence: { $ref: '#/$defs/changeSequence' },
      replayed: { type: 'boolean' },
    },
    additionalProperties: false,
  }),
  deleteAllRequest: namesSchema('delete-all-request', {
    type: 'object',
    properties: {
      idempotencyKey: { $ref: '#/$defs/idempotencyKey' },
      expectedEpoch: { $ref: '#/$defs/epoch' },
    },
    additionalProperties: false,
  }),
  deleteAllResponse: namesSchema('delete-all-response', {
    type: 'object',
    required: ['epoch'],
    properties: {
      epoch: { $ref: '#/$defs/epoch' },
      replayed: { type: 'boolean' },
    },
    additionalProperties: false,
  }),
  snapshotCreateRequest: namesSchema('snapshot-create-request', {
    type: 'object',
    properties: {
      filter: snapshotFilterInline(),
    },
    additionalProperties: false,
  }),
  snapshotCreateResponse: namesSchema('snapshot-create-response', {
    type: 'object',
    required: ['snapshotId', 'epoch', 'feed', 'filterHash', 'watermark', 'memberCount', 'status'],
    properties: {
      snapshotId: { $ref: '#/$defs/snapshotId' },
      epoch: { $ref: '#/$defs/epoch' },
      feed: { $ref: '#/$defs/snapshotFeed' },
      filterHash: { $ref: '#/$defs/filterHash' },
      watermark: { $ref: '#/$defs/changeSequence' },
      // Snapshot membership is an owner-record accounting value. It is not a
      // page length; callers page members separately at MAX_PAGE_RECORDS.
      memberCount: { type: 'integer', minimum: 0, maximum: LIMITS.MAX_RECORDS_PER_OWNER },
      status: { $ref: '#/$defs/snapshotStatus' },
      createdAt: { $ref: '#/$defs/isoDateTime' },
      expiresAt: { $ref: '#/$defs/isoDateTime' },
    },
    additionalProperties: false,
  }),
  snapshotMeta: namesSchema('snapshot-meta', {
    type: 'object',
    required: ['snapshotId', 'epoch', 'feed', 'filterHash', 'watermark', 'status', 'createdAt', 'expiresAt'],
    properties: {
      snapshotId: { $ref: '#/$defs/snapshotId' },
      owner: { $ref: '#/$defs/identityKey' },
      epoch: { $ref: '#/$defs/epoch' },
      feed: { $ref: '#/$defs/snapshotFeed' },
      filterHash: { $ref: '#/$defs/filterHash' },
      filter: snapshotFilterInline(),
      watermark: { $ref: '#/$defs/changeSequence' },
      status: { $ref: '#/$defs/snapshotStatus' },
      createdAt: { $ref: '#/$defs/isoDateTime' },
      expiresAt: { $ref: '#/$defs/isoDateTime' },
    },
    additionalProperties: false,
  }),
  snapshotItem: namesSchema('snapshot-item', {
    type: 'object',
    required: ['recordKey', 'revisionAtW', 'deliveryStateAtW', 'changeSequenceAtW', 'createdAtAtW'],
    properties: {
      recordKey: { $ref: '#/$defs/recordKey' },
      revisionAtW: { $ref: '#/$defs/revision' },
      deliveryStateAtW: { $ref: '#/$defs/deliveryState' },
      changeSequenceAtW: { $ref: '#/$defs/changeSequence' },
      createdAtAtW: { $ref: '#/$defs/isoDateTime' },
    },
    additionalProperties: false,
  }),
  snapshotMembersResponse: namesSchema('snapshot-members-response', {
    type: 'object',
    required: ['status', 'items'],
    properties: {
      status: { $ref: '#/$defs/snapshotStatus' },
      items: {
        type: 'array',
        maxItems: LIMITS.MAX_PAGE_RECORDS,
        items: {
          type: 'object',
          required: ['recordKey', 'revisionAtW', 'deliveryStateAtW', 'changeSequenceAtW', 'createdAtAtW'],
          properties: {
            recordKey: { $ref: '#/$defs/recordKey' },
            revisionAtW: { $ref: '#/$defs/revision' },
            deliveryStateAtW: { $ref: '#/$defs/deliveryState' },
            changeSequenceAtW: { $ref: '#/$defs/changeSequence' },
            createdAtAtW: { $ref: '#/$defs/isoDateTime' },
          },
          additionalProperties: false,
        },
      },
      nextAfter: {
        type: ['object', 'null'],
        properties: {
          createdAtAtW: { $ref: '#/$defs/isoDateTime' },
          recordKey: { $ref: '#/$defs/recordKey' },
        },
        additionalProperties: false,
      },
    },
    additionalProperties: false,
  }),
  snapshotFilter: namesSchema('snapshot-filter', {
    type: 'object',
    properties: {
      direction: { $ref: '#/$defs/direction' },
      messageBox: { $ref: '#/$defs/messageBox' },
      participant: { $ref: '#/$defs/identityKey' },
    },
    additionalProperties: false,
  }),
  capabilities: namesSchema('capabilities', {
    type: 'object',
    required: ['protocolVersion', 'epoch', 'maxRecordsPerOwner', 'maxBytesPerOwner', 'maxBodyBytes', 'maxBatchRecords', 'maxBatchBytes', 'maxPageRecords', 'maxPageBytes', 'retention', 'supportedFeatures'],
    properties: {
      protocolVersion: { type: 'string', const: SCHEMA_VERSION },
      epoch: { $ref: '#/$defs/epoch' },
      maxRecordsPerOwner: { type: 'integer', minimum: 1 },
      maxBytesPerOwner: { type: 'integer', minimum: 1 },
      maxBodyBytes: { type: 'integer', minimum: 1 },
      maxBatchRecords: { type: 'integer', minimum: 1 },
      maxBatchBytes: { type: 'integer', minimum: 1 },
      maxPageRecords: { type: 'integer', minimum: 1 },
      maxPageBytes: { type: 'integer', minimum: 1 },
      retention: { type: 'string' },
      supportedFeatures: { type: 'array', items: { type: 'string', minLength: 1 } },
    },
    additionalProperties: false,
  }),
  storeError: namesSchema('store-error', {
    type: 'object',
    required: ['status', 'code', 'description'],
    properties: {
      status: { type: 'string', const: 'error' },
      code: { $ref: '#/$defs/errorCode' },
      description: { type: 'string', minLength: 1 },
      retryAfterSeconds: { type: 'integer', minimum: 0 },
    },
    additionalProperties: false,
  }),
})
